"""A deliberately small expression language for recipe assertions.

An ``assert`` step in a recipe file is untrusted input.  Recipes get shared on
wikis, pasted out of chat logs, committed by contributors and generated by
assistants; ``eval()`` would hand every one of those the whole Python runtime,
on a machine that is physically wired to a power supply and a CAN bus.  So
nothing here evaluates Python.  The expression is parsed with :mod:`ast` and
walked against an explicit allowlist of node types; anything unrecognised —
a call to something that is not one of seven arithmetic builtins, an import,
an f-string, a lambda, a walrus — is rejected before the recipe compiles, not
while the DUT is energised.

Two properties are worth stating plainly because the rest of the design leans
on them:

* **Attribute access is dictionary lookup, never** ``getattr``.  ``can.frames``
  means ``namespace["can"]["frames"]``.  There is no path from an expression to
  a Python object's attributes, so ``__class__``/``__globals__`` escapes are
  structurally impossible rather than blacklisted.
* **The namespace holds scalars.**  A step result's lists and payloads are
  bound to their *size* (see :func:`scalar_view`), because an assertion is
  about how many frames arrived and how many amps flowed, not about the bytes
  themselves — those are in the capture file, immutable, where they belong.
"""

from __future__ import annotations

import ast
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

from fielddeck.common.errors import RecipeError

__all__ = [
    "ALLOWED_FUNCTIONS",
    "LITERAL_NAMES",
    "MAX_EXPRESSION_CHARS",
    "AssertionOutcome",
    "CompiledExpression",
    "compile_expression",
    "evaluate_assertion",
    "namespace_entry",
    "scalar_view",
]

#: An assertion that needs more than this is a program, and a recipe step is
#: not the place to keep a program.
MAX_EXPRESSION_CHARS = 500
#: Ceiling on parsed nodes.  Bounds evaluation cost for a hostile file.
MAX_NODES = 200
#: Ceiling on nesting depth during evaluation, so recursion cannot blow the
#: interpreter stack from a YAML file.
MAX_DEPTH = 32
#: ``2 ** 10**9`` is a memory bomb with no exception to catch in time, so the
#: exponent must be a small literal.
MAX_POW_EXPONENT = 32
#: Guards ``min``/``max``/``any``/``all`` over literal sequences.
MAX_SEQUENCE_ITEMS = 64
#: Ceiling on the magnitude of any intermediate integer, in bits.
#:
#: The compile-time exponent limit bounds one ``**`` node but does not
#: compose: every exponent in ``(((9**32)**32)**32)`` is a legal small
#: literal, and the result is 9**32768. Nest a few more and the evaluation
#: never returns. Bounding the *result* is what actually closes it, and 4096
#: bits is far beyond anything a real assertion about a bus needs.
MAX_RESULT_BITS = 4096

#: Recipes are YAML, and a YAML author writes ``false``, not ``False``.  These
#: spellings are bound as literals so an assertion reads the way the file around
#: it does; the Python spellings are keywords and parse as constants already.
LITERAL_NAMES: dict[str, Any] = {"true": True, "false": False, "null": None}

#: The only callables an expression may reach.  Every one is pure, total on
#: the values the namespace can hold, and cheap.
ALLOWED_FUNCTIONS: dict[str, Callable[..., Any]] = {
    "len": len,
    "abs": abs,
    "min": min,
    "max": max,
    "round": round,
    "any": any,
    "all": all,
}

_ALLOWED_NODES: tuple[type[ast.AST], ...] = (
    ast.Expression,
    ast.BoolOp,
    ast.UnaryOp,
    ast.BinOp,
    ast.Compare,
    ast.Call,
    ast.Constant,
    ast.Name,
    ast.Attribute,
    ast.Subscript,
    ast.Load,
    ast.Tuple,
    ast.List,
    # operators
    ast.And,
    ast.Or,
    ast.Not,
    ast.USub,
    ast.UAdd,
    ast.Add,
    ast.Sub,
    ast.Mult,
    ast.Div,
    ast.FloorDiv,
    ast.Mod,
    ast.Pow,
    # comparisons
    ast.Eq,
    ast.NotEq,
    ast.Lt,
    ast.LtE,
    ast.Gt,
    ast.GtE,
    ast.In,
    ast.NotIn,
    ast.Is,
    ast.IsNot,
)

_ORDERING_OPS = (ast.Lt, ast.LtE, ast.Gt, ast.GtE)


def _fail(message: str, source: str, **details: Any) -> RecipeError:
    return RecipeError(
        message,
        details={"expression": source, **details},
        preserved="the assertion was not evaluated and no action was taken",
    )


# ---------------------------------------------------------------------------
# Compilation
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class CompiledExpression:
    """A parsed, allowlist-checked expression.

    Compiling is separated from evaluating on purpose: the recipe compiler
    checks every assertion in the file *before* the first action runs, so a
    malformed or malicious expression fails compilation rather than surfacing
    at step nine with an output enabled.
    """

    source: str
    #: Root namespace names the expression reads, e.g. ``("can", "psu")``.
    names: tuple[str, ...]
    tree: ast.Expression = field(repr=False)

    def evaluate(self, namespace: Mapping[str, Any]) -> tuple[Any, dict[str, Any]]:
        """Return ``(value, trace)``.  ``trace`` maps each dotted name that was
        read to the value it had, which is what makes a failure report useful."""
        trace: dict[str, Any] = {}
        value = _eval(self.tree.body, namespace, trace, 0, self.source)
        return value, trace


def compile_expression(source: str) -> CompiledExpression:
    """Parse and vet one assertion expression.  Raises :class:`RecipeError`."""
    text = source.strip()
    if not text:
        raise _fail("assertion expression is empty", source)
    if len(text) > MAX_EXPRESSION_CHARS:
        raise _fail(
            f"assertion expression is {len(text)} characters; the limit is "
            f"{MAX_EXPRESSION_CHARS}. Split it into several assert steps.",
            text[:120],
        )
    try:
        tree = ast.parse(text, mode="eval")
    except SyntaxError as exc:
        raise _fail(
            f"assertion is not a valid expression: {exc.msg}", text, offset=exc.offset
        ) from exc
    except (RecursionError, MemoryError, ValueError) as exc:
        # A pathologically nested expression can exhaust the parser itself.
        raise _fail(f"assertion could not be parsed: {exc}", text) from exc

    nodes = list(ast.walk(tree))
    if len(nodes) > MAX_NODES:
        raise _fail(
            f"assertion has {len(nodes)} parsed elements; the limit is {MAX_NODES}",
            text,
        )
    for node in nodes:
        _vet(node, text)

    called = {
        node.func.id
        for node in nodes
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
    }
    names = tuple(
        sorted(
            {node.id for node in nodes if isinstance(node, ast.Name)} - called - set(LITERAL_NAMES)
        )
    )
    return CompiledExpression(source=text, names=names, tree=tree)


def _vet(node: ast.AST, source: str) -> None:
    """Reject anything not on the allowlist, with the reason spelled out."""
    if not isinstance(node, _ALLOWED_NODES):
        raise _fail(
            f"{type(node).__name__} is not allowed in a recipe assertion. Assertions "
            "may only compare, combine and do arithmetic on step results.",
            source,
            node=type(node).__name__,
        )
    if isinstance(node, ast.Constant):
        if not (node.value is None or isinstance(node.value, (str, int, float, bool))):
            raise _fail(
                f"{type(node.value).__name__} literals are not allowed in an assertion",
                source,
            )
    elif isinstance(node, ast.Name):
        if node.id.startswith("_"):
            raise _fail(f"name {node.id!r} is not readable from an assertion", source)
    elif isinstance(node, ast.Attribute):
        if node.attr.startswith("_"):
            # Redundant given that attribute access is a dict lookup, but a
            # second lock on the door that must never open costs nothing.
            raise _fail(f"attribute {node.attr!r} is not readable from an assertion", source)
    elif isinstance(node, ast.Call):
        _vet_call(node, source)
    elif isinstance(node, ast.BinOp) and isinstance(node.op, ast.Pow):
        exponent = node.right
        if not (
            isinstance(exponent, ast.Constant)
            and isinstance(exponent.value, (int, float))
            and not isinstance(exponent.value, bool)
            and abs(exponent.value) <= MAX_POW_EXPONENT
        ):
            raise _fail(
                f"the exponent of ** must be a literal number no larger than {MAX_POW_EXPONENT}",
                source,
            )


def _vet_call(node: ast.Call, source: str) -> None:
    if not isinstance(node.func, ast.Name):
        raise _fail(
            "only the plain functions "
            f"{', '.join(sorted(ALLOWED_FUNCTIONS))} may be called in an assertion",
            source,
        )
    if node.func.id not in ALLOWED_FUNCTIONS:
        raise _fail(
            f"{node.func.id}() is not available in an assertion; allowed functions are "
            f"{', '.join(sorted(ALLOWED_FUNCTIONS))}",
            source,
            function=node.func.id,
        )
    if node.keywords:
        raise _fail(f"{node.func.id}() takes no keyword arguments in an assertion", source)
    if any(isinstance(arg, ast.Starred) for arg in node.args):
        raise _fail(f"{node.func.id}() may not be called with *args in an assertion", source)
    if len(node.args) > 8:
        raise _fail(f"{node.func.id}() takes at most 8 arguments in an assertion", source)


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------


# One branch per allowed node type.  It is long on purpose: the allowlist and
# the evaluation of each node sit in one place, where a reviewer can check that
# nothing evaluates outside it.
def _eval(
    node: ast.AST, ns: Mapping[str, Any], trace: dict[str, Any], depth: int, source: str
) -> Any:
    if depth > MAX_DEPTH:
        raise _fail("assertion is nested too deeply to evaluate", source)

    if isinstance(node, ast.Constant):
        return node.value

    if isinstance(node, ast.Name):
        if node.id in LITERAL_NAMES:
            return LITERAL_NAMES[node.id]
        if node.id not in ns:
            raise _fail(
                f"no step has produced {node.id!r} yet; available: "
                f"{', '.join(sorted(ns)) or 'nothing'}",
                source,
                name=node.id,
                available=sorted(ns),
            )
        return ns[node.id]

    if isinstance(node, ast.Attribute):
        base = _eval(node.value, ns, trace, depth + 1, source)
        path = _dotted(node)
        if not isinstance(base, Mapping):
            raise _fail(
                f"{_dotted(node.value) or 'that value'} is a value, not a group of "
                f"results, so {node.attr!r} cannot be read from it",
                source,
            )
        if node.attr not in base:
            raise _fail(
                f"{path or node.attr} was not in the step result; that result has "
                f"{', '.join(sorted(str(k) for k in base)) or 'no fields'}",
                source,
                available=sorted(str(k) for k in base),
            )
        value = base[node.attr]
        if path is not None and not isinstance(value, Mapping):
            trace[path] = value
        return value

    if isinstance(node, ast.Subscript):
        return _subscript(node, ns, trace, depth, source)

    if isinstance(node, ast.BoolOp):
        if isinstance(node.op, ast.And):
            result: Any = True
            for value in node.values:
                result = _eval(value, ns, trace, depth + 1, source)
                if not result:
                    return result
            return result
        result = False
        for value in node.values:
            result = _eval(value, ns, trace, depth + 1, source)
            if result:
                return result
        return result

    if isinstance(node, ast.UnaryOp):
        operand = _eval(node.operand, ns, trace, depth + 1, source)
        if isinstance(node.op, ast.Not):
            return not operand
        _require_number(operand, source)
        return -operand if isinstance(node.op, ast.USub) else +operand

    if isinstance(node, ast.BinOp):
        return _binop(node, ns, trace, depth, source)

    if isinstance(node, ast.Compare):
        return _compare(node, ns, trace, depth, source)

    if isinstance(node, ast.Call):
        return _call(node, ns, trace, depth, source)

    if isinstance(node, (ast.Tuple, ast.List)):
        if len(node.elts) > MAX_SEQUENCE_ITEMS:
            raise _fail(
                f"a literal sequence in an assertion may hold at most {MAX_SEQUENCE_ITEMS} items",
                source,
            )
        return [_eval(item, ns, trace, depth + 1, source) for item in node.elts]

    # Unreachable for a compiled expression; kept so a future allowlist entry
    # cannot silently fall through to Python semantics.
    raise _fail(f"{type(node).__name__} cannot be evaluated in an assertion", source)


def _subscript(
    node: ast.Subscript, ns: Mapping[str, Any], trace: dict[str, Any], depth: int, source: str
) -> Any:
    base = _eval(node.value, ns, trace, depth + 1, source)
    key = _eval(node.slice, ns, trace, depth + 1, source)
    if isinstance(base, Mapping):
        if key not in base:
            raise _fail(f"{key!r} is not in that step result", source)
        return base[key]
    if isinstance(base, (str, list, tuple)):
        if not isinstance(key, int) or isinstance(key, bool):
            raise _fail(f"index must be a whole number, got {key!r}", source)
        if not -len(base) <= key < len(base):
            raise _fail(f"index {key} is outside a sequence of {len(base)} items", source)
        return base[key]
    raise _fail(f"{type(base).__name__} values cannot be indexed in an assertion", source)


def _binop(
    node: ast.BinOp, ns: Mapping[str, Any], trace: dict[str, Any], depth: int, source: str
) -> Any:
    left = _eval(node.left, ns, trace, depth + 1, source)
    right = _eval(node.right, ns, trace, depth + 1, source)
    # Numbers only: ``"x" * 10**6`` and friends are how a text expression turns
    # into a memory exhaustion bug.
    _require_number(left, source)
    _require_number(right, source)
    try:
        if isinstance(node.op, ast.Add):
            return left + right
        if isinstance(node.op, ast.Sub):
            return left - right
        if isinstance(node.op, ast.Mult):
            return left * right
        if isinstance(node.op, ast.Div):
            return left / right
        if isinstance(node.op, ast.FloorDiv):
            return left // right
        if isinstance(node.op, ast.Mod):
            return left % right
        if isinstance(node.op, ast.Mult):  # pragma: no cover - handled above
            return left * right
        _check_pow_magnitude(left, right, source)
        return left**right
    except ZeroDivisionError:
        raise _fail(f"division by zero while evaluating {source!r}", source) from None
    except (OverflowError, ValueError) as exc:
        raise _fail(f"arithmetic overflowed while evaluating {source!r}: {exc}", source) from exc


def _check_pow_magnitude(base: Any, exponent: Any, source: str) -> None:
    """Refuse an exponentiation whose *result* would be enormous.

    Checked on the values rather than on the syntax, because the operands may
    themselves be computed. Python has no way to interrupt a large integer
    power once it starts, so the only useful place to say no is before it.
    """
    if not isinstance(base, int) or isinstance(base, bool):
        return
    if not isinstance(exponent, int) or exponent < 0:
        return
    bits = base.bit_length() * exponent
    if bits > MAX_RESULT_BITS:
        raise _fail(
            f"{source!r} would produce a {bits}-bit number; assertions are limited "
            f"to {MAX_RESULT_BITS} bits so a recipe cannot exhaust memory",
            source,
        )


def _compare(
    node: ast.Compare, ns: Mapping[str, Any], trace: dict[str, Any], depth: int, source: str
) -> bool:
    left = _eval(node.left, ns, trace, depth + 1, source)
    for op, comparator in zip(node.ops, node.comparators, strict=True):
        right = _eval(comparator, ns, trace, depth + 1, source)
        if not _compare_one(left, op, right, source):
            return False
        left = right
    return True


def _compare_one(left: Any, op: ast.cmpop, right: Any, source: str) -> bool:
    if isinstance(op, ast.Eq):
        return bool(left == right)
    if isinstance(op, ast.NotEq):
        return bool(left != right)
    if isinstance(op, (ast.Is, ast.IsNot)):
        if left is not None and right is not None:
            raise _fail(
                "'is' only compares against None in an assertion; use == to compare values",
                source,
            )
        return (left is right) if isinstance(op, ast.Is) else (left is not right)
    if isinstance(op, (ast.In, ast.NotIn)):
        if not isinstance(right, (str, list, tuple, Mapping)):
            raise _fail(f"'in' needs text or a list on the right, got {right!r}", source)
        contained = left in right
        return contained if isinstance(op, ast.In) else not contained
    if isinstance(op, _ORDERING_OPS):
        _require_comparable(left, right, source)
        if isinstance(op, ast.Lt):
            return bool(left < right)
        if isinstance(op, ast.LtE):
            return bool(left <= right)
        if isinstance(op, ast.Gt):
            return bool(left > right)
        return bool(left >= right)
    raise _fail(f"{type(op).__name__} comparisons are not allowed in an assertion", source)


def _call(
    node: ast.Call, ns: Mapping[str, Any], trace: dict[str, Any], depth: int, source: str
) -> Any:
    assert isinstance(node.func, ast.Name)  # guaranteed by _vet_call
    name = node.func.id
    func = ALLOWED_FUNCTIONS[name]
    args = [_eval(arg, ns, trace, depth + 1, source) for arg in node.args]
    try:
        return func(*args)
    except TypeError as exc:
        if name == "len" and args and isinstance(args[0], int):
            raise _fail(
                f"len() got a number. Results that were lists are already bound to "
                f"their item count, so write the name on its own: {_dotted(node.args[0]) or 'x'}",
                source,
            ) from exc
        raise _fail(f"{name}() cannot be applied to those values: {exc}", source) from exc
    except ValueError as exc:
        raise _fail(f"{name}() failed: {exc}", source) from exc


def _require_number(value: Any, source: str) -> None:
    if not isinstance(value, (int, float)):
        raise _fail(
            f"arithmetic in an assertion needs numbers, got {type(value).__name__} {value!r}",
            source,
        )


def _require_comparable(left: Any, right: Any, source: str) -> None:
    if isinstance(left, (int, float)) and isinstance(right, (int, float)):
        return
    if isinstance(left, str) and isinstance(right, str):
        return
    raise _fail(
        f"cannot order {type(left).__name__} against {type(right).__name__} "
        f"({left!r} and {right!r}). Compare numbers with numbers.",
        source,
    )


def _dotted(node: ast.AST) -> str | None:
    """``can.frames`` for an attribute chain rooted in a name, else ``None``."""
    parts: list[str] = []
    current = node
    while isinstance(current, ast.Attribute):
        parts.append(current.attr)
        current = current.value
    if not isinstance(current, ast.Name):
        return None
    parts.append(current.id)
    return ".".join(reversed(parts))


# ---------------------------------------------------------------------------
# The namespace an assertion reads
# ---------------------------------------------------------------------------


def scalar_view(value: Any, *, depth: int = 3) -> Any:
    """Project one result value into what an assertion may see.

    Numbers, text and booleans pass through untouched — a voltage is never
    rounded or coerced on its way to an assertion.  Anything with a size
    (a frame list, a byte payload, a nested result group at maximum depth)
    binds to that size, because ``can.frames > 0`` is asking whether traffic
    was observed.  The frames themselves live in the capture file.
    """
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, (bytes, bytearray, memoryview)):
        return len(value)
    if isinstance(value, Mapping):
        if depth <= 0:
            return len(value)
        return {
            str(key): scalar_view(item, depth=depth - 1)
            for key, item in value.items()
            if isinstance(key, str)
        }
    if isinstance(value, Sequence):
        return len(value)
    # Anything else (an object, a stray driver type) has no honest scalar
    # projection, so it reads as absent rather than as a misleading string.
    return None


def namespace_entry(result: Mapping[str, Any], *, max_keys: int = 256) -> dict[str, Any]:
    """The scalar view of one action result, ready to merge into a namespace."""
    entry: dict[str, Any] = {}
    for key, value in result.items():
        if len(entry) >= max_keys:
            break
        if not isinstance(key, str) or key.startswith("_"):
            continue
        entry[key] = scalar_view(value)
    return entry


# ---------------------------------------------------------------------------
# Assertions
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class AssertionOutcome:
    passed: bool
    value: Any
    #: What the operator needs to see: the expression with the values it read.
    detail: str
    referenced: dict[str, Any]

    def as_dict(self) -> dict[str, Any]:
        return {
            "passed": self.passed,
            "value": self.value if isinstance(self.value, (bool, int, float, str)) else None,
            "detail": self.detail,
            "values": self.referenced,
        }


def evaluate_assertion(
    compiled: CompiledExpression, namespace: Mapping[str, Any]
) -> AssertionOutcome:
    """Evaluate one assertion and describe the result in operator terms.

    Raises :class:`RecipeError` when the expression cannot be evaluated at all
    (an unknown name, an impossible comparison).  A well-formed expression that
    is simply false comes back as ``passed=False`` — that is a test result, not
    an error.
    """
    value, trace = compiled.evaluate(namespace)
    passed = bool(value)
    if trace:
        read = ", ".join(f"{name}={_render(item)}" for name, item in sorted(trace.items()))
        detail = f"{compiled.source}  [{read}]"
    else:
        detail = compiled.source
    return AssertionOutcome(passed=passed, value=value, detail=detail, referenced=dict(trace))


def _render(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:g}"
    return repr(value) if isinstance(value, str) else str(value)
