"""What a recipe file is allowed to say — and nothing more.

A recipe is YAML, which means it is the part of FieldDeck most likely to have
been written by someone who is not in the room: copied off a wiki, generated by
an assistant, committed by a contributor who has never seen your bench.  So the
parser is strict on purpose.  Unknown keys are refused rather than ignored,
because a silently dropped ``current_limit`` is a recipe that energises a DUT
with the previous setpoint still in place.  Every error names the phase and the
step index, because "invalid recipe" at 2am is not a diagnosis.

Shapes accepted for one step, all equivalent to the engine:

    - action: psu.set          # an action, parameters inline
      device: role:psu
      voltage: 24.0

    - action: psu.set          # the same, parameters grouped
      params: {device: role:psu, voltage: 24.0}

    - wait: 2                  # or:  {action: wait, seconds: 2}
    - assert: "can.frames > 0" # or:  {assert: {expression: ..., message: ...}}
    - mark: power-up           # lowered to the real session.mark action
    - note: "clip the probe"   # lowered to the real session.note action
    - repeat: {count: 3, steps: [...]}

Parameters are literals.  There is deliberately no templating or interpolation
into an action's parameters: it is what lets the compiler check every voltage in
the file against the effective limits *before* anything runs, with no runtime
value able to slip past.
"""

from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Any, Literal

import yaml
from pydantic import ConfigDict, Field, ValidationError, model_validator

from fielddeck.common.errors import RecipeError
from fielddeck.common.models import DeviceRole, SafetyLimit, StrictModel
from fielddeck.common.paths import Paths, default_paths

__all__ = [
    "ActionStep",
    "AssertStep",
    "DeviceRequirement",
    "LoadedRecipe",
    "MarkStep",
    "NoteStep",
    "Recipe",
    "RecipeLimits",
    "RecipePhase",
    "RecipeSource",
    "RepeatStep",
    "Requires",
    "Step",
    "StepKind",
    "WaitStep",
    "list_recipe_files",
    "load_recipe_file",
    "load_recipe_text",
    "recipe_roots",
    "resolve_recipe_reference",
]

#: A recipe is configuration, not data.  Anything larger is a mistake or an
#: attempt to make the parser the interesting part of the program.
MAX_RECIPE_BYTES = 512 * 1024
#: Steps written in one phase, before ``repeat`` expansion.
MAX_STEPS_PER_PHASE = 500
#: How deeply ``repeat`` may nest.
MAX_REPEAT_DEPTH = 3
#: Recipe format versions this build understands.
SUPPORTED_VERSIONS = frozenset({1})

#: Keys on an action step that belong to the *engine*, not to the action.
#: Everything else on the step is a parameter, so an action gaining a new
#: parameter never needs a change here.
RESERVED_STEP_KEYS = frozenset({"action", "params", "store", "timeout_s"})

_YAML_SUFFIXES = (".yaml", ".yml")


class StepKind(StrEnum):
    ACTION = "action"
    WAIT = "wait"
    ASSERT = "assert"
    MARK = "mark"
    NOTE = "note"
    REPEAT = "repeat"


class RecipePhase(StrEnum):
    """``finally`` runs whatever happened to ``steps``."""

    STEPS = "steps"
    FINALLY = "finally"


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------


class _BaseStep(StrictModel):
    #: Index within the list it was written in, so an error can point at it.
    source_index: int = 0


class ActionStep(_BaseStep):
    kind: Literal[StepKind.ACTION] = StepKind.ACTION
    action: str = Field(min_length=1, max_length=120)
    params: dict[str, Any] = Field(default_factory=dict)
    #: Namespace the result is filed under for later assertions.  Defaults to
    #: the action's own prefix, so ``can.capture`` fills ``can``.
    store: str | None = Field(default=None, min_length=1, max_length=40)
    timeout_s: float | None = Field(default=None, gt=0, le=3600)

    @property
    def device(self) -> str | None:
        reference = self.params.get("device")
        return reference if isinstance(reference, str) else None

    @property
    def namespace(self) -> str:
        return self.store or self.action.split(".", 1)[0]


class WaitStep(_BaseStep):
    kind: Literal[StepKind.WAIT] = StepKind.WAIT
    seconds: float = Field(gt=0, le=3600)


class AssertStep(_BaseStep):
    kind: Literal[StepKind.ASSERT] = StepKind.ASSERT
    expression: str = Field(min_length=1, max_length=500)
    message: str | None = Field(default=None, max_length=500)


class MarkStep(_BaseStep):
    """A label on the unified timeline.  Lowered to ``session.mark``."""

    kind: Literal[StepKind.MARK] = StepKind.MARK
    label: str = Field(min_length=1, max_length=120)
    note: str | None = Field(default=None, max_length=500)


class NoteStep(_BaseStep):
    """Free text in the session record.  Lowered to ``session.note``."""

    kind: Literal[StepKind.NOTE] = StepKind.NOTE
    text: str = Field(min_length=1, max_length=2000)


class RepeatStep(_BaseStep):
    kind: Literal[StepKind.REPEAT] = StepKind.REPEAT
    count: int = Field(ge=1, le=1000)
    steps: list[Step]


Step = Annotated[
    ActionStep | WaitStep | AssertStep | MarkStep | NoteStep | RepeatStep,
    Field(discriminator="kind"),
]

RepeatStep.model_rebuild()


# ---------------------------------------------------------------------------
# Recipe
# ---------------------------------------------------------------------------


class DeviceRequirement(StrictModel):
    """One device the recipe cannot run without, named by role or by id."""

    role: DeviceRole | None = None
    id: str | None = None
    note: str | None = Field(default=None, max_length=200)

    @model_validator(mode="after")
    def _exactly_one(self) -> DeviceRequirement:
        if (self.role is None) == (self.id is None):
            raise ValueError("give exactly one of 'role:' or 'id:' for each required device")
        return self

    @property
    def reference(self) -> str:
        """How the registry will be asked for it."""
        return f"role:{self.role}" if self.role is not None else str(self.id)


class Requires(StrictModel):
    devices: list[DeviceRequirement] = Field(default_factory=list, max_length=32)

    @model_validator(mode="before")
    @classmethod
    def _accept_bare_references(cls, data: Any) -> Any:
        """``- role:psu`` and ``- can:can0`` are as clear as the mapping form."""
        if not isinstance(data, dict):
            return data
        devices = data.get("devices")
        if not isinstance(devices, list):
            return data
        converted: list[Any] = []
        for entry in devices:
            if isinstance(entry, str) and entry.startswith("role:"):
                converted.append({"role": entry.split(":", 1)[1]})
            elif isinstance(entry, str):
                converted.append({"id": entry})
            else:
                converted.append(entry)
        return {**data, "devices": converted}


class LimitBound(StrictModel):
    maximum: float | None = None
    minimum: float | None = None

    @model_validator(mode="after")
    def _at_least_one(self) -> LimitBound:
        if self.maximum is None and self.minimum is None:
            raise ValueError("a limit needs a maximum, a minimum, or both")
        return self


class RecipeLimits(StrictModel):
    """The envelope the recipe says it stays inside.

    These can only *tighten* what the deployment allows.  A recipe asking for
    more headroom than ``safety.yaml`` permits was written for a different
    bench, and the compiler refuses it rather than quietly clamping — clamping
    would run a test that is not the test the author described.
    """

    voltage_max: float | None = Field(default=None, ge=0)
    current_max: float | None = Field(default=None, ge=0)
    power_max: float | None = Field(default=None, ge=0)
    #: Anything the three shorthands do not cover, e.g. ``gpio.voltage``.
    quantities: dict[str, LimitBound] = Field(default_factory=dict, max_length=32)

    @model_validator(mode="before")
    @classmethod
    def _accept_both_spellings(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data
        renamed = {"max_voltage": "voltage_max", "max_current": "current_max"}
        renamed["max_power"] = "power_max"
        out = dict(data)
        for old, new in renamed.items():
            if old in out:
                if new in out:
                    raise ValueError(f"give either {old} or {new}, not both")
                out[new] = out.pop(old)
        return out

    def as_limits(self) -> dict[str, SafetyLimit]:
        """The declared envelope as limits the enforcer understands."""
        limits: dict[str, SafetyLimit] = {}
        for quantity, maximum in (
            ("psu.voltage", self.voltage_max),
            ("psu.current", self.current_max),
            ("psu.power", self.power_max),
        ):
            if maximum is not None:
                limits[quantity] = SafetyLimit(quantity=quantity, maximum=maximum, minimum=0.0)
        for quantity, bound in self.quantities.items():
            declared = SafetyLimit(quantity=quantity, maximum=bound.maximum, minimum=bound.minimum)
            existing = limits.get(quantity)
            limits[quantity] = declared if existing is None else existing.intersect(declared)
        return limits

    def describe(self) -> dict[str, dict[str, float | None]]:
        return {
            quantity: {"minimum": limit.minimum, "maximum": limit.maximum}
            for quantity, limit in sorted(self.as_limits().items())
        }


class Recipe(StrictModel):
    """One parsed recipe file.  What it says, not yet what it will do."""

    model_config = ConfigDict(populate_by_name=True)

    version: int = 1
    name: str = Field(min_length=1, max_length=120)
    description: str | None = Field(default=None, max_length=2000)
    requires: Requires = Field(default_factory=Requires)
    limits: RecipeLimits = Field(default_factory=RecipeLimits)
    steps: list[Step] = Field(default_factory=list, max_length=MAX_STEPS_PER_PHASE)
    #: ``finally`` is a Python keyword, hence the trailing underscore.  YAML
    #: always spells it ``finally``.
    finally_: list[Step] = Field(
        default_factory=list, alias="finally", max_length=MAX_STEPS_PER_PHASE
    )

    def phase(self, phase: RecipePhase) -> list[Step]:
        return self.steps if phase is RecipePhase.STEPS else self.finally_


@dataclass(frozen=True, slots=True)
class RecipeSource:
    """Where a recipe came from, so a session report can prove which file ran."""

    path: str | None
    sha256: str
    size_bytes: int

    def describe(self) -> dict[str, Any]:
        return {"path": self.path, "sha256": self.sha256, "size_bytes": self.size_bytes}


@dataclass(frozen=True, slots=True)
class LoadedRecipe:
    recipe: Recipe
    source: RecipeSource


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _step_error(
    message: str, *, phase: str, index: int, kind: str | None = None, **details: Any
) -> RecipeError:
    where = f"{phase} step {index}"
    return RecipeError(
        f"{where}: {message}",
        details={"phase": phase, "step": index, "kind": kind, **details},
        preserved="the recipe was not compiled and nothing was run",
    )


def _validation_problems(exc: ValidationError) -> list[dict[str, str]]:
    return [
        {"field": ".".join(str(part) for part in err["loc"]) or "(step)", "problem": err["msg"]}
        for err in exc.errors()
    ]


def _build(model: type[Any], data: dict[str, Any], *, phase: str, index: int, kind: str) -> Any:
    try:
        return model.model_validate({**data, "source_index": index})
    except ValidationError as exc:
        problems = _validation_problems(exc)
        first = problems[0]
        raise _step_error(
            f"{first['field']}: {first['problem']}",
            phase=phase,
            index=index,
            kind=kind,
            errors=problems,
        ) from exc


def _parse_step(raw: Any, *, phase: str, index: int, depth: int) -> Step:
    if not isinstance(raw, dict):
        raise _step_error(
            f"expected a mapping, got {type(raw).__name__}",
            phase=phase,
            index=index,
        )
    keys = set(raw)
    if not keys:
        raise _step_error("is empty", phase=phase, index=index)

    # Key-form kinds first.  ``mark`` is checked before ``note`` so that
    # ``{mark: power-up, note: "..."}`` is one annotated mark, not two steps.
    if "assert" in keys:
        return _parse_assert(raw, phase=phase, index=index)
    if "wait" in keys:
        return _build(WaitStep, {"seconds": raw["wait"]}, phase=phase, index=index, kind="wait")
    if "mark" in keys:
        return _build(
            MarkStep,
            {"label": raw["mark"], "note": raw.get("note")},
            phase=phase,
            index=index,
            kind="mark",
        )
    if "note" in keys:
        return _build(NoteStep, {"text": raw["note"]}, phase=phase, index=index, kind="note")
    if "repeat" in keys:
        return _parse_repeat(raw["repeat"], phase=phase, index=index, depth=depth)
    if "action" in keys:
        return _parse_action(raw, phase=phase, index=index, depth=depth)

    raise _step_error(
        "has no 'action' and is not a wait/assert/mark/note/repeat step "
        f"(keys were: {', '.join(sorted(str(k) for k in keys))})",
        phase=phase,
        index=index,
        keys=sorted(str(k) for k in keys),
    )


def _parse_assert(raw: dict[str, Any], *, phase: str, index: int) -> AssertStep:
    body = raw["assert"]
    if isinstance(body, str):
        data = {"expression": body, "message": raw.get("message")}
    elif isinstance(body, dict):
        extra = set(body) - {"expression", "message"}
        if extra:
            raise _step_error(
                f"assert takes 'expression' and 'message'; got {', '.join(sorted(extra))}",
                phase=phase,
                index=index,
                kind="assert",
            )
        data = {"expression": body.get("expression"), "message": body.get("message")}
    else:
        raise _step_error(
            "assert takes an expression string or a mapping with 'expression'",
            phase=phase,
            index=index,
            kind="assert",
        )
    return _build(AssertStep, data, phase=phase, index=index, kind="assert")


def _parse_repeat(body: Any, *, phase: str, index: int, depth: int) -> RepeatStep:
    if depth >= MAX_REPEAT_DEPTH:
        raise _step_error(
            f"repeat is nested more than {MAX_REPEAT_DEPTH} deep",
            phase=phase,
            index=index,
            kind="repeat",
        )
    if not isinstance(body, dict):
        raise _step_error(
            "repeat takes a mapping with 'count' and 'steps'",
            phase=phase,
            index=index,
            kind="repeat",
        )
    extra = set(body) - {"count", "steps"}
    if extra:
        raise _step_error(
            f"repeat takes 'count' and 'steps'; got {', '.join(sorted(extra))}",
            phase=phase,
            index=index,
            kind="repeat",
        )
    nested = _parse_steps(
        body.get("steps"), phase=f"{phase}[repeat@{index}]", depth=depth + 1, required=True
    )
    return _build(
        RepeatStep,
        {"count": body.get("count"), "steps": nested},
        phase=phase,
        index=index,
        kind="repeat",
    )


def _parse_action(raw: dict[str, Any], *, phase: str, index: int, depth: int) -> Step:
    name = raw["action"]
    if not isinstance(name, str) or not name.strip():
        raise _step_error("'action' must name an action", phase=phase, index=index)
    name = name.strip()

    # The two conceptual step kinds that read naturally as actions.  Both
    # spellings appear in the specification's examples, and refusing one of
    # them would only make recipes harder to write, not safer.
    if name == "wait":
        _reject_unexpected(raw, {"action", "seconds"}, phase=phase, index=index, kind="wait")
        return _build(
            WaitStep, {"seconds": raw.get("seconds")}, phase=phase, index=index, kind="wait"
        )
    if name == "assert":
        _reject_unexpected(
            raw, {"action", "expression", "message"}, phase=phase, index=index, kind="assert"
        )
        return _build(
            AssertStep,
            {"expression": raw.get("expression"), "message": raw.get("message")},
            phase=phase,
            index=index,
            kind="assert",
        )
    if name == "repeat":
        return _parse_repeat(
            {"count": raw.get("count"), "steps": raw.get("steps")},
            phase=phase,
            index=index,
            depth=depth,
        )

    inline = {key: value for key, value in raw.items() if key not in RESERVED_STEP_KEYS}
    explicit = raw.get("params")
    if explicit is not None and inline:
        raise _step_error(
            "give parameters inline or under 'params:', not both "
            f"(inline: {', '.join(sorted(inline))})",
            phase=phase,
            index=index,
            kind="action",
        )
    params = explicit if explicit is not None else inline
    if not isinstance(params, dict) or any(not isinstance(key, str) for key in params):
        raise _step_error(
            "parameters must be a mapping with text keys",
            phase=phase,
            index=index,
            kind="action",
        )
    return _build(
        ActionStep,
        {
            "action": name,
            "params": params,
            "store": raw.get("store"),
            "timeout_s": raw.get("timeout_s"),
        },
        phase=phase,
        index=index,
        kind="action",
    )


def _reject_unexpected(
    raw: dict[str, Any], allowed: set[str], *, phase: str, index: int, kind: str
) -> None:
    extra = set(raw) - allowed
    if extra:
        raise _step_error(
            f"{kind} takes {', '.join(sorted(allowed - {'action'}))}; "
            f"got {', '.join(sorted(str(key) for key in extra))}",
            phase=phase,
            index=index,
            kind=kind,
        )


def _parse_steps(raw: Any, *, phase: str, depth: int = 0, required: bool = False) -> list[Step]:
    if raw is None:
        if required:
            raise RecipeError(
                f"{phase} has no steps",
                details={"phase": phase},
                preserved="the recipe was not compiled and nothing was run",
            )
        return []
    if not isinstance(raw, list):
        raise RecipeError(
            f"{phase} must be a list of steps, got {type(raw).__name__}",
            details={"phase": phase},
            preserved="the recipe was not compiled and nothing was run",
        )
    if len(raw) > MAX_STEPS_PER_PHASE:
        raise RecipeError(
            f"{phase} has {len(raw)} steps; the limit is {MAX_STEPS_PER_PHASE}",
            details={"phase": phase, "steps": len(raw)},
            preserved="the recipe was not compiled and nothing was run",
        )
    return [
        _parse_step(entry, phase=phase, index=index, depth=depth) for index, entry in enumerate(raw)
    ]


def parse_recipe(data: Any) -> Recipe:
    """Validate an already-decoded recipe document."""
    if not isinstance(data, dict):
        raise RecipeError(
            f"a recipe must be a YAML mapping, got {type(data).__name__}",
            preserved="nothing was run",
        )
    version = data.get("version", 1)
    if version not in SUPPORTED_VERSIONS:
        raise RecipeError(
            f"recipe format version {version!r} is not supported by this build "
            f"(supported: {', '.join(str(v) for v in sorted(SUPPORTED_VERSIONS))})",
            details={"version": version},
            preserved="nothing was run",
        )
    payload = dict(data)
    payload["steps"] = _parse_steps(payload.get("steps"), phase=str(RecipePhase.STEPS))
    payload["finally"] = _parse_steps(payload.pop("finally", None), phase=str(RecipePhase.FINALLY))
    payload.pop("finally_", None)
    try:
        return Recipe.model_validate(payload)
    except ValidationError as exc:
        problems = _validation_problems(exc)
        first = problems[0]
        raise RecipeError(
            f"recipe is invalid: {first['field']}: {first['problem']}",
            details={"errors": problems},
            preserved="nothing was run",
        ) from exc


def load_recipe_text(text: str, *, path: str | None = None) -> LoadedRecipe:
    """Parse recipe YAML.  ``safe_load`` only: no object construction."""
    raw = text.encode("utf-8")
    if len(raw) > MAX_RECIPE_BYTES:
        raise RecipeError(
            f"recipe is {len(raw)} bytes; the limit is {MAX_RECIPE_BYTES}",
            details={"path": path},
            preserved="nothing was read into the engine",
        )
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise RecipeError(
            f"{path or 'recipe'} is not valid YAML: {exc}",
            details={"path": path},
            preserved="nothing was run",
        ) from exc
    recipe = parse_recipe(data)
    return LoadedRecipe(
        recipe=recipe,
        source=RecipeSource(path=path, sha256=hashlib.sha256(raw).hexdigest(), size_bytes=len(raw)),
    )


def load_recipe_file(path: Path) -> LoadedRecipe:
    try:
        if path.stat().st_size > MAX_RECIPE_BYTES:
            raise RecipeError(
                f"{path} is larger than the {MAX_RECIPE_BYTES} byte recipe limit",
                details={"path": str(path)},
                preserved="the file was not read",
            )
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise RecipeError(
            f"cannot read recipe {path}: {exc}",
            details={"path": str(path)},
            preserved="nothing was run",
        ) from exc
    except UnicodeDecodeError as exc:
        raise RecipeError(
            f"{path} is not UTF-8 text; recipes are YAML files",
            details={"path": str(path)},
            preserved="nothing was run",
        ) from exc
    return load_recipe_text(text, path=str(path))


# ---------------------------------------------------------------------------
# Finding recipes on disk
# ---------------------------------------------------------------------------


def recipe_roots(paths: Paths | None = None) -> list[Path]:
    """Directories a recipe may be loaded from, most specific first.

    Recipes are read by the daemon, which runs as the instrument authority, so
    the set of directories it will read from is fixed rather than "whatever
    path the caller passed".  ``FIELDDECK_RECIPES_DIR`` is how an operator adds
    their own; the working-directory entry is what makes a git checkout work
    without installing anything.
    """
    paths = paths or default_paths()
    candidates: list[Path] = []
    override = os.environ.get("FIELDDECK_RECIPES_DIR")
    if override:
        candidates.extend(Path(part).expanduser() for part in override.split(os.pathsep) if part)
    candidates.append(paths.config_dir / "recipes")
    candidates.append(paths.state_dir / "recipes")
    candidates.append(Path.cwd() / "recipes")

    roots: list[Path] = []
    for candidate in candidates:
        try:
            resolved = candidate.resolve()
        except OSError:  # pragma: no cover - unreadable mount
            continue
        if resolved.is_dir() and resolved not in roots:
            roots.append(resolved)
    return roots


def list_recipe_files(roots: list[Path] | None = None, *, limit: int = 200) -> list[Path]:
    """Every recipe file in the search roots and their immediate subdirectories."""
    found: list[Path] = []
    for root in roots if roots is not None else recipe_roots():
        for suffix in _YAML_SUFFIXES:
            found.extend(sorted(root.glob(f"*{suffix}")))
            found.extend(sorted(root.glob(f"*/*{suffix}")))
        if len(found) >= limit:
            break
    unique: list[Path] = []
    for path in found:
        if path not in unique and path.is_file():
            unique.append(path)
    return unique[:limit]


def resolve_recipe_reference(reference: str, roots: list[Path] | None = None) -> Path:
    """Turn ``controller-smoke-test`` or a path into a file inside a known root.

    A recipe reference arrives from a CLI argument, an MCP call or another
    recipe, so it is treated as hostile: the resolved file must live inside one
    of the recipe roots.  ``../../etc/`` and a symlink pointing out of the tree
    are refused the same way.
    """
    if not reference or not reference.strip():
        raise RecipeError("no recipe was named", preserved="nothing was run")
    reference = reference.strip()
    search = roots if roots is not None else recipe_roots()
    if not search:
        raise RecipeError(
            "no recipe directory exists on this unit; create one or set FIELDDECK_RECIPES_DIR",
            details={"looked_in": [str(p) for p in recipe_roots()]},
            preserved="nothing was run",
        )

    candidates: list[Path] = []
    as_path = Path(reference).expanduser()
    if as_path.is_absolute():
        candidates.append(as_path)
    elif as_path.suffix in _YAML_SUFFIXES or "/" in reference:
        candidates.extend(root / as_path for root in search)
    else:
        for root in search:
            for suffix in _YAML_SUFFIXES:
                candidates.append(root / f"{reference}{suffix}")
                candidates.extend(sorted(root.glob(f"*/{reference}{suffix}")))

    for candidate in candidates:
        try:
            resolved = candidate.resolve()
        except OSError:  # pragma: no cover - unreadable mount
            continue
        if not resolved.is_file():
            continue
        if not any(resolved.is_relative_to(root) for root in search):
            raise RecipeError(
                f"{resolved} is outside the recipe directories; copy it into one of "
                f"{', '.join(str(root) for root in search)} first",
                details={"path": str(resolved), "roots": [str(root) for root in search]},
                preserved="the file was not read",
            )
        return resolved

    known = [path.stem for path in list_recipe_files(search)]
    raise RecipeError(
        f"no recipe named {reference!r} in {', '.join(str(root) for root in search)}",
        details={"reference": reference, "available": known},
        preserved="nothing was run",
    )
