"""The recipe expression evaluator, mostly from the attacker's side.

An ``assert`` step is untrusted input.  Recipes get shared on wikis, pasted out
of chat logs, committed by contributors and generated by assistants, and they
run on a machine physically wired to a power supply and a CAN bus.  ``eval()``
would hand every one of those the whole Python runtime.

Two structural properties do the heavy lifting, and both are tested here rather
than assumed:

* **Attribute access is a dictionary lookup, never ``getattr``.**  ``can.frames``
  means ``namespace["can"]["frames"]``.  There is no path from an expression to
  a Python object, so ``__class__`` escapes are impossible rather than
  blacklisted — the blacklist is belt and braces.
* **The namespace holds scalars.**  A frame list binds to its length, because
  an assertion is about how many frames arrived, not about the bytes; the bytes
  are in the capture file, immutable, where they belong.
"""

from __future__ import annotations

from typing import Any

import pytest

from fielddeck.common.errors import RecipeError
from fielddeck.recipes.assertions import (
    ALLOWED_FUNCTIONS,
    MAX_EXPRESSION_CHARS,
    compile_expression,
    evaluate_assertion,
    namespace_entry,
    scalar_view,
)

NAMESPACE: dict[str, Any] = {
    "can": {"frames": 12, "count": 12, "errors": 0, "nested": {"depth": 1}},
    "psu": {"voltage": 24.0, "current": 0.42, "output": True, "name": "psu-a"},
    "serial": {"bytes": 2491, "chunks": 302},
}


def run(expression: str, namespace: dict[str, Any] | None = None):
    return evaluate_assertion(compile_expression(expression), namespace or NAMESPACE)


# ---------------------------------------------------------------------------
# Malicious input
# ---------------------------------------------------------------------------


class TestRejectsMaliciousInput:
    @pytest.mark.parametrize(
        "expression",
        [
            '__import__("os").system("id")',
            'open("/etc/passwd").read()',
            "(1).__class__.__bases__",
            "psu.__class__",
            "psu.__dict__",
            "can.__getitem__",
            "().__class__.__mro__[1].__subclasses__()",
            "globals()",
            "locals()",
            "eval('1')",
            "exec('x=1')",
            "compile('1', '', 'eval')",
            "getattr(psu, 'voltage')",
            "vars()",
            "dir()",
            "input()",
            "print(psu.voltage)",
            "help()",
            "breakpoint()",
        ],
    )
    def test_escapes_and_side_effects_are_refused_at_compile_time(
        self, expression: str
    ) -> None:
        """Refused before the recipe runs, not while the DUT is energised."""
        with pytest.raises(RecipeError) as caught:
            compile_expression(expression)
        assert caught.value.preserved == (
            "the assertion was not evaluated and no action was taken"
        )

    @pytest.mark.parametrize(
        "expression",
        [
            "lambda: 1",
            "[x for x in range(3)]",
            "{k: 1 for k in range(3)}",
            '{"a": 1}',
            "f'{psu.voltage}'",
            "(y := 3)",
            "1 if true else 2",
            "yield 1",
            "await x",
            "psu.voltage = 60",
            "import os",
            "del psu",
        ],
    )
    def test_anything_that_is_not_a_comparison_is_refused(self, expression: str) -> None:
        """Assertions may compare, combine and do arithmetic.  Nothing else."""
        with pytest.raises(RecipeError):
            compile_expression(expression)

    def test_only_the_seven_arithmetic_builtins_are_reachable(self) -> None:
        assert set(ALLOWED_FUNCTIONS) == {"len", "abs", "min", "max", "round", "any", "all"}
        for name in ALLOWED_FUNCTIONS:
            assert compile_expression(f"{name}([1, 2]) == {name}([1, 2])")

    def test_an_attribute_lookup_never_reaches_a_python_object(self) -> None:
        """The structural guarantee, stated as a test.

        ``psu`` is a plain dict in the namespace.  If attribute access were
        ``getattr`` this would return a bound method; instead it is a missing
        key, and the error says which keys exist.
        """
        with pytest.raises(RecipeError) as caught:
            run("psu.keys")
        assert "was not in the step result" in str(caught.value)


class TestResourceBombs:
    def test_a_huge_exponent_is_refused_at_compile_time(self) -> None:
        """``2 ** 10**9`` is a memory bomb with no exception to catch in time."""
        with pytest.raises(RecipeError, match="exponent"):
            compile_expression("2 ** 10**9")

    def test_nested_small_exponents_are_caught_by_the_result_bound(self) -> None:
        """Every exponent here is a legal small literal; the result is not."""
        with pytest.raises(RecipeError, match="bit number"):
            run("(((9**32)**32)**32)**32 > 0")

    def test_string_multiplication_is_not_arithmetic(self) -> None:
        with pytest.raises(RecipeError, match="needs numbers"):
            run('"a" * 10**9 == ""')

    def test_an_over_long_expression_is_refused_with_advice(self) -> None:
        with pytest.raises(RecipeError, match="Split it into several assert steps"):
            compile_expression("1 + " * (MAX_EXPRESSION_CHARS // 2) + "1")

    def test_a_deeply_nested_expression_is_refused_before_the_stack_is(self) -> None:
        """Recursion in the evaluator is bounded, so a YAML file cannot blow
        the interpreter stack."""
        expression = "len(" * 40 + "[1]" + ")" * 40
        with pytest.raises(RecipeError, match="nested too deeply"):
            evaluate_assertion(compile_expression(expression), {})

    def test_redundant_parentheses_are_not_nesting(self) -> None:
        """Grouping produces no AST nodes, so it is neither a bomb nor a
        problem — worth pinning so the depth guard is not "fixed" to reject it."""
        assert evaluate_assertion(compile_expression("(" * 60 + "1" + ")" * 60), {}).value == 1

    def test_an_empty_expression_is_refused(self) -> None:
        with pytest.raises(RecipeError, match="empty"):
            compile_expression("   ")


# ---------------------------------------------------------------------------
# What a recipe author actually writes
# ---------------------------------------------------------------------------


class TestEverydayExpressions:
    @pytest.mark.parametrize(
        ("expression", "expected"),
        [
            ("can.frames > 0", True),
            ("can.frames > 100", False),
            ("psu.voltage == 24.0", True),
            ("psu.current > 0.05 and psu.current < 1.0", True),
            ("psu.output", True),
            ("not psu.output", False),
            ("psu.name == 'psu-a'", True),
            ("serial.bytes > 0 and serial.chunks > 1", True),
            ("can.errors == 0", True),
            ("can.frames in [11, 12, 13]", True),
            ("abs(psu.voltage - 24.0) < 0.5", True),
            ("round(psu.current, 1) == 0.4", True),
            ("min(can.frames, 100) == 12", True),
            ("can['frames'] == 12", True),
            ("can.nested.depth == 1", True),
        ],
    )
    def test_ordinary_assertions_evaluate(self, expression: str, expected: bool) -> None:
        assert run(expression).passed is expected

    def test_yaml_spellings_of_the_literals_are_accepted(self) -> None:
        """A recipe author writes ``false``, not ``False``; the file is YAML."""
        assert run("true and not false").passed is True
        assert run("null == null").passed is True

    def test_a_failing_assertion_is_a_result_not_an_error(self) -> None:
        outcome = run("psu.current > 99.0")
        assert outcome.passed is False
        assert outcome.detail == "psu.current > 99.0  [psu.current=0.42]"

    def test_the_detail_shows_every_value_that_was_read(self) -> None:
        """What the operator needs at 2am: the expression and its inputs."""
        outcome = run("psu.voltage > 12 and can.frames > 0")
        assert "psu.voltage=24" in outcome.detail
        assert "can.frames=12" in outcome.detail
        assert outcome.referenced == {"psu.voltage": 24.0, "can.frames": 12}

    def test_the_compiled_expression_reports_the_names_it_needs(self) -> None:
        """Which is how the compiler knows an assertion refers to a step that
        has not run yet."""
        compiled = compile_expression("can.frames > 0 and psu.voltage < 30")
        assert compiled.names == ("can", "psu")
        assert "len" not in compile_expression("len([1,2]) == 2").names


class TestEvaluationErrors:
    def test_an_unknown_namespace_lists_what_is_available(self) -> None:
        with pytest.raises(RecipeError) as caught:
            run("nope.thing > 1")
        assert "no step has produced 'nope' yet" in str(caught.value)
        assert "can, psu, serial" in str(caught.value)

    def test_a_missing_key_lists_the_keys_that_exist(self) -> None:
        with pytest.raises(RecipeError) as caught:
            run("can.voltage > 1")
        assert "was not in the step result" in str(caught.value)
        assert "frames" in str(caught.value)

    def test_ordering_a_number_against_text_is_refused(self) -> None:
        """Python would happily compare in some versions and explode in others;
        an instrument should just say what went wrong."""
        with pytest.raises(RecipeError, match="cannot order"):
            run("psu.voltage > 'x'")

    def test_division_by_zero_is_reported_as_an_assertion_problem(self) -> None:
        with pytest.raises(RecipeError):
            run("psu.voltage / can.errors > 1")


# ---------------------------------------------------------------------------
# The scalar view
# ---------------------------------------------------------------------------


class TestScalarView:
    def test_numbers_text_and_booleans_pass_through_untouched(self) -> None:
        """A voltage is never rounded or coerced on its way to an assertion."""
        for value in (24.000001, -3, "CV", True, False, None):
            assert scalar_view(value) == value

    @pytest.mark.parametrize(
        ("value", "expected"),
        [
            ([1, 2, 3], 3),
            ((1, 2), 2),
            (b"\x00\x01\x02", 3),
            (bytearray(5), 5),
            (memoryview(b"abcd"), 4),
        ],
    )
    def test_anything_with_a_size_binds_to_that_size(self, value: Any, expected: int) -> None:
        assert scalar_view(value) == expected

    def test_nested_results_are_projected_to_a_bounded_depth(self) -> None:
        deep = {"a": {"b": {"c": {"d": {"e": 1}}}}}
        assert scalar_view(deep) == {"a": {"b": {"c": 1}}}

    def test_an_opaque_object_reads_as_absent_rather_than_as_text(self) -> None:
        """A stray driver object has no honest scalar projection, and a
        misleading string would be worse than nothing."""

        class Driver:
            pass

        assert scalar_view(Driver()) is None

    def test_a_namespace_entry_hides_private_keys(self) -> None:
        entry = namespace_entry({"frames": [1, 2, 3], "_internal": 1, "count": 3})
        assert entry == {"frames": 3, "count": 3}

    def test_a_namespace_entry_is_bounded(self) -> None:
        entry = namespace_entry({f"k{index}": index for index in range(1000)}, max_keys=10)
        assert len(entry) == 10

    def test_a_frame_list_reads_as_its_length_which_is_what_recipes_ask(self) -> None:
        outcome = evaluate_assertion(
            compile_expression("can.frames > 0"),
            {"can": namespace_entry({"frames": [{"id": 1}, {"id": 2}]})},
        )
        assert outcome.passed is True
        assert outcome.referenced == {"can.frames": 2}
