"""The recipe parser, which is the most exposed input surface FieldDeck has.

A recipe is YAML written by someone who is probably not in the room: copied off
a wiki, generated by an assistant, committed by a contributor who has never
seen this bench.  So the parser is strict on purpose — an unknown key is a
refusal, not a shrug.  A silently dropped ``current_limit`` is a recipe that
energises a DUT with whatever setpoint happened to be left over.

The other thing these tests pin is the error's *usefulness*: every refusal has
to name the phase and the step index, because "invalid recipe" at 2am is not a
diagnosis.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from fielddeck.common.errors import RecipeError
from fielddeck.common.models import DeviceRole
from fielddeck.common.paths import Paths
from fielddeck.recipes.schema import (
    MAX_RECIPE_BYTES,
    MAX_REPEAT_DEPTH,
    ActionStep,
    AssertStep,
    MarkStep,
    NoteStep,
    RecipePhase,
    RepeatStep,
    StepKind,
    WaitStep,
    list_recipe_files,
    load_recipe_file,
    load_recipe_text,
    recipe_roots,
    resolve_recipe_reference,
)

MINIMAL = """
version: 1
name: minimal
steps:
  - action: system.status
"""


def parse(text: str):
    return load_recipe_text(text, path="test.yaml").recipe


# ---------------------------------------------------------------------------
# Step forms
# ---------------------------------------------------------------------------


class TestStepForms:
    def test_parameters_may_be_inline_or_grouped(self) -> None:
        """Both spellings appear in the documentation; both mean the same."""
        inline = parse(
            "version: 1\nname: n\nsteps:\n"
            "  - action: psu.set\n    device: role:psu\n    voltage: 24.0\n"
        ).steps[0]
        grouped = parse(
            "version: 1\nname: n\nsteps:\n"
            "  - action: psu.set\n    params: {device: role:psu, voltage: 24.0}\n"
        ).steps[0]

        assert isinstance(inline, ActionStep) and isinstance(grouped, ActionStep)
        assert inline.params == grouped.params == {"device": "role:psu", "voltage": 24.0}
        assert inline.device == "role:psu"

    def test_engine_keys_are_not_passed_to_the_action(self) -> None:
        step = parse(
            "version: 1\nname: n\nsteps:\n"
            "  - action: can.capture\n    device: sim:can:can0\n"
            "    store: bus\n    timeout_s: 30\n    duration_s: 2\n"
        ).steps[0]
        assert isinstance(step, ActionStep)
        assert step.params == {"device": "sim:can:can0", "duration_s": 2}
        assert step.store == "bus"
        assert step.timeout_s == 30

    def test_the_result_namespace_defaults_to_the_action_prefix(self) -> None:
        step = parse("version: 1\nname: n\nsteps:\n  - action: can.capture\n").steps[0]
        assert isinstance(step, ActionStep)
        assert step.namespace == "can"

    @pytest.mark.parametrize(
        ("text", "kind", "check"),
        [
            ("  - wait: 2\n", StepKind.WAIT, lambda s: s.seconds == 2),
            (
                "  - action: wait\n    seconds: 2\n",
                StepKind.WAIT,
                lambda s: s.seconds == 2,
            ),
            (
                '  - assert: "can.frames > 0"\n',
                StepKind.ASSERT,
                lambda s: s.expression == "can.frames > 0",
            ),
            (
                '  - assert:\n      expression: "can.frames > 0"\n      message: nothing arrived\n',
                StepKind.ASSERT,
                lambda s: s.message == "nothing arrived",
            ),
            ("  - mark: power-up\n", StepKind.MARK, lambda s: s.label == "power-up"),
            ("  - note: clip the probe\n", StepKind.NOTE, lambda s: s.text == "clip the probe"),
        ],
    )
    def test_every_documented_shorthand_parses(self, text: str, kind: StepKind, check) -> None:
        step = parse(f"version: 1\nname: n\nsteps:\n{text}").steps[0]
        assert step.kind is kind
        assert check(step)

    def test_a_mark_with_a_note_is_one_annotated_mark(self) -> None:
        """Not two steps: ``mark`` is checked before ``note`` for exactly this."""
        step = parse(
            "version: 1\nname: n\nsteps:\n  - mark: power-up\n    note: probe on TP4\n"
        ).steps[0]
        assert isinstance(step, MarkStep)
        assert step.note == "probe on TP4"

    def test_repeat_expands_nothing_at_parse_time_but_keeps_its_body(self) -> None:
        step = parse(
            "version: 1\nname: n\nsteps:\n"
            "  - repeat:\n      count: 3\n      steps:\n        - wait: 1\n"
        ).steps[0]
        assert isinstance(step, RepeatStep)
        assert step.count == 3
        assert isinstance(step.steps[0], WaitStep)

    def test_finally_is_spelled_the_yaml_way(self) -> None:
        recipe = parse(
            "version: 1\nname: n\nsteps:\n  - wait: 1\nfinally:\n  - mark: done\n"
        )
        assert isinstance(recipe.finally_[0], MarkStep)
        assert recipe.phase(RecipePhase.FINALLY) == recipe.finally_
        assert recipe.phase(RecipePhase.STEPS) == recipe.steps

    def test_steps_remember_where_they_were_written(self) -> None:
        recipe = parse("version: 1\nname: n\nsteps:\n  - wait: 1\n  - wait: 2\n  - wait: 3\n")
        assert [step.source_index for step in recipe.steps] == [0, 1, 2]


# ---------------------------------------------------------------------------
# Refusals
# ---------------------------------------------------------------------------


class TestRefusals:
    def test_an_unknown_top_level_key_is_refused(self) -> None:
        with pytest.raises(RecipeError) as caught:
            parse("version: 1\nname: n\nstepz:\n  - wait: 1\n")
        assert "stepz" in str(caught.value)

    def test_an_unknown_step_kind_lists_the_keys_it_saw(self) -> None:
        with pytest.raises(RecipeError) as caught:
            parse("version: 1\nname: n\nsteps:\n  - device: role:psu\n    voltage: 24\n")
        assert "no 'action'" in str(caught.value)
        assert caught.value.details["keys"] == ["device", "voltage"]

    def test_an_error_names_the_phase_and_the_index(self) -> None:
        """"Invalid recipe" is not a diagnosis; "finally step 1" is."""
        with pytest.raises(RecipeError) as caught:
            parse("version: 1\nname: n\nsteps:\n  - wait: 1\nfinally:\n  - wait: 1\n  - {}\n")
        assert caught.value.details["phase"] == "finally"
        assert caught.value.details["step"] == 1

    def test_an_unsupported_version_is_refused_with_the_supported_set(self) -> None:
        with pytest.raises(RecipeError) as caught:
            parse("version: 99\nname: n\nsteps: []\n")
        assert caught.value.details["version"] == 99
        assert "supported: 1" in str(caught.value)

    def test_a_recipe_must_be_a_mapping(self) -> None:
        with pytest.raises(RecipeError, match="must be a YAML mapping"):
            parse("- just\n- a\n- list\n")

    def test_invalid_yaml_is_refused_with_its_path(self) -> None:
        with pytest.raises(RecipeError) as caught:
            load_recipe_text("steps: [unclosed\n", path="broken.yaml")
        assert "not valid YAML" in str(caught.value)
        assert caught.value.details["path"] == "broken.yaml"

    def test_an_over_sized_recipe_is_refused_before_it_is_parsed(self) -> None:
        """A recipe is configuration, not data."""
        with pytest.raises(RecipeError) as caught:
            load_recipe_text("# " + "x" * MAX_RECIPE_BYTES)
        assert caught.value.preserved == "nothing was read into the engine"

    def test_assert_takes_only_an_expression_and_a_message(self) -> None:
        with pytest.raises(RecipeError, match="assert takes"):
            parse(
                "version: 1\nname: n\nsteps:\n"
                '  - assert:\n      expression: "1 == 1"\n      retry: 3\n'
            )

    def test_repeat_cannot_nest_forever(self) -> None:
        body = "  - repeat:\n      count: 2\n      steps:\n"
        text = "version: 1\nname: n\nsteps:\n"
        indent = "  "
        for depth in range(MAX_REPEAT_DEPTH + 1):
            text += indent * depth + body.replace("\n  ", "\n" + indent * depth + "  ")
        text += indent * (MAX_REPEAT_DEPTH + 1) + "    - wait: 1\n"
        with pytest.raises(RecipeError):
            parse(text)

    def test_a_step_that_is_not_a_mapping_is_refused(self) -> None:
        with pytest.raises(RecipeError, match="expected a mapping"):
            parse("version: 1\nname: n\nsteps:\n  - just a string\n")

    def test_an_empty_step_is_refused(self) -> None:
        with pytest.raises(RecipeError, match="is empty"):
            parse("version: 1\nname: n\nsteps:\n  - {}\n")

    def test_a_recipe_needs_a_name(self) -> None:
        with pytest.raises(RecipeError):
            parse("version: 1\nsteps:\n  - wait: 1\n")


# ---------------------------------------------------------------------------
# Requirements and limits
# ---------------------------------------------------------------------------


class TestRequires:
    def test_devices_may_be_named_by_role_or_by_id(self) -> None:
        recipe = parse(
            "version: 1\nname: n\nrequires:\n  devices:\n"
            "    - role: psu\n    - id: sim:can:can0\n"
            "steps:\n  - wait: 1\n"
        )
        assert recipe.requires.devices[0].role is DeviceRole.PSU
        assert recipe.requires.devices[0].reference == "role:psu"
        assert recipe.requires.devices[1].reference == "sim:can:can0"

    def test_a_bare_string_is_as_clear_as_the_mapping_form(self) -> None:
        recipe = parse(
            "version: 1\nname: n\nrequires:\n  devices: [role:psu, sim:can:can0]\n"
            "steps:\n  - wait: 1\n"
        )
        assert [device.reference for device in recipe.requires.devices] == [
            "role:psu",
            "sim:can:can0",
        ]

    def test_a_device_needs_exactly_one_of_role_or_id(self) -> None:
        with pytest.raises(RecipeError, match="exactly one"):
            parse(
                "version: 1\nname: n\nrequires:\n  devices:\n"
                "    - {role: psu, id: sim:visa:sim-psu-0}\n"
                "steps:\n  - wait: 1\n"
            )

    def test_an_unknown_role_is_refused(self) -> None:
        with pytest.raises(RecipeError):
            parse(
                "version: 1\nname: n\nrequires:\n  devices:\n    - role: teleporter\n"
                "steps:\n  - wait: 1\n"
            )


class TestLimits:
    def test_the_declared_envelope_becomes_real_limits(self) -> None:
        recipe = parse(
            "version: 1\nname: n\nlimits:\n"
            "  voltage_max: 12.0\n  current_max: 1.0\n  power_max: 10.0\n"
            "steps:\n  - wait: 1\n"
        )
        limits = recipe.limits.as_limits()
        assert limits["psu.voltage"].maximum == 12.0
        assert limits["psu.current"].maximum == 1.0
        assert limits["psu.power"].maximum == 10.0
        # A declared ceiling implies a floor of zero, not an unbounded negative.
        assert limits["psu.voltage"].minimum == 0.0

    def test_both_spellings_of_the_shorthands_are_accepted(self) -> None:
        assert (
            parse(
                "version: 1\nname: n\nlimits:\n  max_voltage: 12.0\nsteps:\n  - wait: 1\n"
            ).limits.voltage_max
            == 12.0
        )

    def test_giving_both_spellings_at_once_is_refused(self) -> None:
        with pytest.raises(RecipeError):
            parse(
                "version: 1\nname: n\nlimits:\n  max_voltage: 12.0\n  voltage_max: 24.0\n"
                "steps:\n  - wait: 1\n"
            )

    def test_an_arbitrary_quantity_can_be_bounded(self) -> None:
        recipe = parse(
            "version: 1\nname: n\nlimits:\n"
            "  quantities:\n    gpio.voltage: {maximum: 3.3}\n"
            "steps:\n  - wait: 1\n"
        )
        assert recipe.limits.as_limits()["gpio.voltage"].maximum == 3.3

    def test_a_limit_with_neither_bound_is_meaningless_and_refused(self) -> None:
        with pytest.raises(RecipeError):
            parse(
                "version: 1\nname: n\nlimits:\n  quantities:\n    gpio.voltage: {}\n"
                "steps:\n  - wait: 1\n"
            )


# ---------------------------------------------------------------------------
# Provenance and file resolution
# ---------------------------------------------------------------------------


class TestSourceProvenance:
    def test_the_source_hash_proves_which_file_ran(self) -> None:
        loaded = load_recipe_text(MINIMAL, path="minimal.yaml")
        assert loaded.source.path == "minimal.yaml"
        assert len(loaded.source.sha256) == 64
        assert loaded.source.size_bytes == len(MINIMAL.encode("utf-8"))

    def test_an_edited_recipe_hashes_differently(self) -> None:
        first = load_recipe_text(MINIMAL).source.sha256
        second = load_recipe_text(MINIMAL.replace("system.status", "device.list")).source.sha256
        assert first != second


class TestFileResolution:
    @pytest.fixture
    def recipe_dir(self, paths: Paths, monkeypatch: pytest.MonkeyPatch) -> Path:
        root = paths.config_dir / "recipes"
        (root / "nested").mkdir(parents=True)
        (root / "smoke.yaml").write_text(MINIMAL, encoding="utf-8")
        (root / "nested" / "deep.yml").write_text(MINIMAL, encoding="utf-8")
        monkeypatch.setenv("FIELDDECK_RECIPES_DIR", str(root))
        # ``./recipes`` is one of the search roots, and running pytest from the
        # repository would otherwise pull in the shipped examples.
        monkeypatch.chdir(paths.home)
        return root

    def test_a_bare_name_resolves_inside_a_known_root(self, recipe_dir: Path) -> None:
        assert resolve_recipe_reference("smoke") == recipe_dir / "smoke.yaml"

    def test_an_immediate_subdirectory_is_searched_too(self, recipe_dir: Path) -> None:
        assert resolve_recipe_reference("deep") == recipe_dir / "nested" / "deep.yml"

    def test_listing_finds_every_recipe_file(self, recipe_dir: Path) -> None:
        found = {path.name for path in list_recipe_files()}
        assert found == {"smoke.yaml", "deep.yml"}

    def test_a_path_outside_the_roots_is_refused(
        self, recipe_dir: Path, tmp_path: Path
    ) -> None:
        """The reference arrives from a CLI argument or an MCP call, so it is
        treated as hostile."""
        outside = tmp_path / "elsewhere.yaml"
        outside.write_text(MINIMAL, encoding="utf-8")

        with pytest.raises(RecipeError) as caught:
            resolve_recipe_reference(str(outside))
        assert caught.value.preserved == "the file was not read"

    def test_traversal_out_of_a_root_is_refused(self, recipe_dir: Path) -> None:
        with pytest.raises(RecipeError):
            resolve_recipe_reference("../../../etc/passwd")

    def test_a_symlink_pointing_out_of_the_tree_is_refused(
        self, recipe_dir: Path, tmp_path: Path
    ) -> None:
        outside = tmp_path / "outside.yaml"
        outside.write_text(MINIMAL, encoding="utf-8")
        (recipe_dir / "sneaky.yaml").symlink_to(outside)

        with pytest.raises(RecipeError, match="outside the recipe directories"):
            resolve_recipe_reference("sneaky")

    def test_an_unknown_name_lists_what_is_available(self, recipe_dir: Path) -> None:
        with pytest.raises(RecipeError) as caught:
            resolve_recipe_reference("does-not-exist")
        assert set(caught.value.details["available"]) == {"smoke", "deep"}

    def test_an_empty_reference_is_refused(self, recipe_dir: Path) -> None:
        with pytest.raises(RecipeError, match="no recipe was named"):
            resolve_recipe_reference("   ")

    def test_the_roots_are_a_fixed_set_not_whatever_was_passed(
        self, recipe_dir: Path, paths: Paths, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.delenv("FIELDDECK_RECIPES_DIR", raising=False)
        monkeypatch.chdir(paths.home)
        roots = recipe_roots(paths)
        assert all(root.is_dir() for root in roots)
        assert (paths.config_dir / "recipes").resolve() in roots

    def test_several_roots_may_be_given_at_once(
        self, recipe_dir: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        other = tmp_path / "more-recipes"
        other.mkdir()
        (other / "extra.yaml").write_text(MINIMAL, encoding="utf-8")
        monkeypatch.setenv("FIELDDECK_RECIPES_DIR", os.pathsep.join([str(recipe_dir), str(other)]))

        assert resolve_recipe_reference("extra") == other / "extra.yaml"
        assert {path.stem for path in list_recipe_files()} == {"smoke", "deep", "extra"}


class TestFixtureRecipes:
    """The checked-in fixtures must stay parseable, since other tests use them."""

    @pytest.mark.parametrize(
        "name", ["passive-listen", "power-up", "over-limit", "malicious-assert"]
    )
    def test_the_fixture_recipes_parse(self, fixtures_dir: Path, name: str) -> None:
        loaded = load_recipe_file(fixtures_dir / "recipes" / f"{name}.yaml")
        assert loaded.recipe.name == name
        assert loaded.source.path.endswith(f"{name}.yaml")

    def test_the_broken_fixture_is_refused(self, fixtures_dir: Path) -> None:
        with pytest.raises(RecipeError):
            load_recipe_file(fixtures_dir / "recipes" / "unknown-key.yaml")

    def test_a_missing_file_is_reported_rather_than_crashing(self, tmp_path: Path) -> None:
        with pytest.raises(RecipeError) as caught:
            load_recipe_file(tmp_path / "nope.yaml")
        assert caught.value.preserved == "nothing was run"

    def test_a_binary_file_is_not_a_recipe(self, tmp_path: Path) -> None:
        target = tmp_path / "firmware.yaml"
        target.write_bytes(b"\x7fELF\x02\x01\x01\x00\xff\xfe")
        with pytest.raises(RecipeError):
            load_recipe_file(target)


class TestPhaseModel:
    def test_an_action_step_reports_no_device_when_it_names_none(self) -> None:
        step = parse("version: 1\nname: n\nsteps:\n  - action: system.status\n").steps[0]
        assert isinstance(step, ActionStep)
        assert step.device is None

    def test_assert_steps_carry_their_message_for_the_failure_report(self) -> None:
        step = parse(
            'version: 1\nname: n\nsteps:\n  - assert:\n      expression: "1 == 1"\n'
            "      message: the rail did not come up\n"
        ).steps[0]
        assert isinstance(step, AssertStep)
        assert step.message == "the rail did not come up"

    def test_note_steps_keep_their_text_verbatim(self) -> None:
        step = parse("version: 1\nname: n\nsteps:\n  - note: |\n      two\n      lines\n").steps[0]
        assert isinstance(step, NoteStep)
        assert step.text == "two\nlines\n"
